Changing the logic
Signed-off-by: cmoulliard <cmoulliard@redhat.com>

diff --git a/.github/workflows/kubevirt.yml b/.github/workflows/kubevirt.yml
--- a/.github/workflows/kubevirt.yml
+++ b/.github/workflows/kubevirt.yml
@@ -186,29 +186,43 @@ jobs:
            kubectl apply -f pipelines/pipelines/quarkus-maven-build.yaml
            kubectl apply -f pipelines/pipelineruns/quarkus-maven-build-run.yaml
            
-           echo "Wait a few second till the pipelineRun is created/started"
-           sleep 10s
-           tkn pipelinerun describe quarkus-maven-build-run
+           #echo "Wait a few second till the pipelineRun is created/started"
+           #sleep 10s
+           #tkn pipelinerun describe quarkus-maven-build-run
            
-           while true; do
-             STATUS=$(tkn pipelinerun describe quarkus-maven-build-run -o json | jq -r '.status.conditions[] | select(.reason=="Completed") | true')
-             if [ "$STATUS" == "true" ]; then
-                echo "Pipeline run succeeded."
-                break
-             else
-                echo "###################### BEGIN ####################################"
-                echo "PipelineRun is still running ..."
-                RESPONSE=$(tkn pipelinerun describe quarkus-maven-build-run -o json | jq -r '.status.conditions[] | .message')
-                if [[ "$RESPONSE" =~ "Failed" ]]; then
-                   tkn pipelinerun describe quarkus-maven-build-run
-                   tkn taskrun describe quarkus-maven-build-run-maven-test
-                   tkn taskrun logs quarkus-maven-build-run-maven-test
-                   exit 1
-                fi
-                echo "###################### END ####################################"
+           STATUS=$(kubectl get pipelinerun quarkus-maven-build-run -o json | jq -rc .status.conditions[0].status)
+           LIMIT=$((SECONDS+360))
+           while [ "${STATUS}" != "Unknown" ]; do
+             if [ $SECONDS -gt $LIMIT ]
+             then
+               echo "Timeout waiting for PipelineRun to complete"
+               exit 2
              fi
              sleep 20
+             echo "Waiting for PipelineRun to complete"
+             kubectl get pipelinerun quarkus-maven-build-run -o json | jq -rc .status.conditions[0]
+             STATUS=$(kubectl get pipelinerun quarkus-maven-build-run -o json | jq -rc .status.conditions[0].status)
            done
+           
+           #while true; do
+           #  STATUS=$(tkn pipelinerun describe quarkus-maven-build-run -o json | jq -r '.status.conditions[] | select(.reason=="Completed") | true')
+           #  if [ "$STATUS" == "true" ]; then
+           #     echo "Pipeline run succeeded."
+           #     break
+           #  else
+           #     echo "###################### BEGIN ####################################"
+           #     echo "PipelineRun is still running ..."
+           #     RESPONSE=$(tkn pipelinerun describe quarkus-maven-build-run -o json | jq -r '.status.conditions[] | .message')
+           #     if [[ "$RESPONSE" =~ "Failed" ]]; then
+           #        tkn pipelinerun describe quarkus-maven-build-run
+           #        tkn taskrun describe quarkus-maven-build-run-maven-test
+           #        tkn taskrun logs quarkus-maven-build-run-maven-test
+           #        exit 1
+           #     fi
+           #     echo "###################### END ####################################"
+           #  fi
+           #  sleep 20
+           #done
 
        - name: (Only if it succeeded) Log messages
          if: success()
