Log the pipelinerun since the beginning
Signed-off-by: cmoulliard <cmoulliard@redhat.com>

diff --git a/.github/workflows/kubevirt.yml b/.github/workflows/kubevirt.yml
--- a/.github/workflows/kubevirt.yml
+++ b/.github/workflows/kubevirt.yml
@@ -187,22 +187,24 @@ jobs:
            kubectl apply -f pipelines/pipelineruns/quarkus-maven-build-run.yaml
            
            #echo "Wait a few second till the pipelineRun is created/started"
-           #sleep 10s
-           #tkn pipelinerun describe quarkus-maven-build-run
+           # tkn pipelinerun describe quarkus-maven-build-run
+           sleep 10s
            
-           STATUS=$(kubectl get pipelinerun quarkus-maven-build-run -o json | jq -rc .status.conditions[0].status)
-           LIMIT=$((SECONDS+360))
-           while [ "${STATUS}" != "Failed" ]; do
-             if [ $SECONDS -gt $LIMIT ]; then
-               echo "Timeout waiting for PipelineRun to complete"
-               exit 2
-            else
-               tkn pipelinerun logs quarkus-maven-build-run
-             fi
-             sleep 20
-             echo "Waiting for PipelineRun to complete ..."
-             STATUS=$(kubectl get pipelinerun quarkus-maven-build-run -o json | jq -rc .status.conditions[0].status)
-           done
+           tkn pipelinerun logs quarkus-maven-build-run -f
+           
+           #STATUS=$(kubectl get pipelinerun quarkus-maven-build-run -o json | jq -rc .status.conditions[0].status)
+           #LIMIT=$((SECONDS+360))
+           #while [ "${STATUS}" != "Failed" ]; do
+           #  if [ $SECONDS -gt $LIMIT ]; then
+           #    echo "Timeout waiting for PipelineRun to complete"
+           #    exit 2
+           # else
+           #    tkn pipelinerun logs quarkus-maven-build-run
+           #  fi
+           #  sleep 20
+           #  echo "Waiting for PipelineRun to complete ..."
+           #  STATUS=$(kubectl get pipelinerun quarkus-maven-build-run -o json | jq -rc .status.conditions[0].status)
+           #done
            
            #while true; do
            #  STATUS=$(tkn pipelinerun describe quarkus-maven-build-run -o json | jq -r '.status.conditions[] | select(.reason=="Completed") | true')
